# Working with Tensors in Tensorflow

In [48]:
import tensorflow as tf
import numpy as np

# only use 1GB of GPU (allows having multiple notebooks open simultaneously)
gpus = tf.config.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only allocate 1GB of memory on the first GPU
  try:
    tf.config.set_logical_device_configuration(
        gpus[0],
        [tf.config.LogicalDeviceConfiguration(memory_limit=1024)])
    logical_gpus = tf.config.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e)

# What is a tensor? 

- **A Tensor is a generalization of the concepts scalar, vector and matrix**

Rank 0 tensor: **scalar** with shape () e.g. 5

Rank 1 tensor: **vector** with shape (n) e.g. $\begin{pmatrix}1 \\ 2 \\ 3 \end{pmatrix}$


Rank 2 tensor: **matrix** with shape (m,n) e.g. $\begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$

Rank 3 tensor: e.g. **image** with shape (width, height, color channels)

Rank 4 tensor: e.g. RGB video with shape (time, width, height, color channels)

Rank 5 tensor: e.g. batch of RGB videos with shape (batch_size, time, width, height, color channels)

.
.
.

# Creating tensors from other objects in Python

In [49]:
to_tensor = 5.0

to_tensor = [ [1,2,3], \
              [4,5,6] ]

#to_tensor = np.arange(1,7)
#to_tensor = np.ones((2,3))
#to_tensor = np.random.randn(5,2,3)


tensor = tf.constant(to_tensor, 
                    dtype=tf.float32
                    )
print(tensor)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


# Creating tensors directly with Tensorflow

In [51]:
tensor = tf.ones(shape=(3,2))

tensor = tf.random.normal((3,2))

# generate tensor filled with random integers
#tensor = tf.random.uniform((4,3,2), minval= 0, maxval=100, dtype=tf.int32)

print(tensor)

tf.Tensor(
[[ 0.96278054  1.4377793 ]
 [ 0.29934168  0.01113588]
 [ 0.89502406 -0.00584318]], shape=(3, 2), dtype=float32)


# Reshaping and transposing tensors

In [53]:
tensor = tf.range(1,101, dtype=tf.float32)
print(tensor.shape, "\n")

# reshaping
reshaped_tensor = tf.reshape(tensor, (20,5))
print(reshaped_tensor.shape, "\n")

# adding a dimension of 1: e.g. from tensor shape (32,10) -> (32,10,1)
expanded_tensor = tf.expand_dims(tensor, axis=-1)
print(expanded_tensor.shape, "\n")

# removing dimensions of 1: e.g. (1,20,1,20,1) -> (20,20)
squeezed_tensor = tf.squeeze(expanded_tensor, axis=None)
print(squeezed_tensor.shape, "\n")

# transposing

transposed_tensor = tf.transpose(reshaped_tensor)
print(transposed_tensor.shape, "\n")

# transposing with permutation: e.g. (10,5,2) -> (5,10,2)
permuted_tensor = tf.transpose(reshaped_tensor, perm=[1,0])
print(permuted_tensor.shape)

(100,) 

(20, 5) 

(100, 1) 

(100,) 

(5, 20) 

(5, 20)


# Concatenating tensors

In [54]:
A = tf.ones((128,12,12,15), dtype=tf.float32)

B = tf.zeros((128,12,12,35), dtype=tf.float32)


tf.concat([A,B], axis= -1)


<tf.Tensor: shape=(128, 12, 12, 50), dtype=float32, numpy=
array([[[[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]],

        ...,

        [[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 1., ...

# Stacking tensors

In [20]:
A = tf.ones((32,15,7), dtype=tf.float32)

B = tf.zeros((32,15,7), dtype=tf.float32)

tf.stack([A,B], axis=0)

<tf.Tensor: shape=(2, 32, 15, 7), dtype=float32, numpy=
array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1

# Reduce-operations in tensorflow

- instead of sum, we use reduce_sum and specify the axis over which we want to sum.
- same for other operations like mean, std, product etc.

In [55]:
tensor = tf.ones((32,4,2))
print(tensor.shape,"\n")

feature_sum = tf.reduce_sum(tensor, axis=1)
print(feature_sum.shape, "\n")

batch_sum = tf.reduce_prod(tensor, axis=0)
print(batch_sum.shape, "\n")

total_sum = tf.reduce_mean(tensor, axis=None)
print(total_sum.shape)

total_std = tf.math.reduce_std(tensor,axis=None)
print(total_std.shape)

(32, 4, 2) 

(32, 2) 

(4, 2) 

()
()


# Matrix multiplication and other operations with tensors

In [57]:
A = tf.ones((32,2,5))
B = tf.ones((32, 5,10))

result = tf.matmul(A,B)
#result = A@B
print(result.shape)

(32, 2, 10)


In [59]:
# element-wise operations

A = tf.range(1,6, dtype=tf.float32)
B = tf.ones(A.shape)*0.5 # broadcast multiplication by 0.5 
print(B*A)

tf.Tensor([0.5 1.  1.5 2.  2.5], shape=(5,), dtype=float32)


# Constants and variables

- Tensors can be constants or variables

- Constants should be used for data (immutable), variables for model parameters (mutable with variable.assign(...))

- Variables can be flagged as trainable or non-trainable

In [60]:
var = tf.Variable([1,2,3], trainable = True, dtype=tf.float32, name="weight_1")
print(var)

<tf.Variable 'weight_1:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


In [40]:
var.assign([2,3,4])
print(var)

<tf.Variable 'weight_1:0' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>


# Converting current variable values to a constant tensor

- Can be useful for keeping track of model parameters during training

In [41]:
stored_tensor = tf.convert_to_tensor(var)

In [42]:
print(stored_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


# Converting tensors to a different dtype

In [61]:
# before transforming, we have float32
print(stored_tensor.dtype)

tf.cast(stored_tensor, dtype=tf.int8)

<dtype: 'float32'>


<tf.Tensor: shape=(3,), dtype=int8, numpy=array([2, 3, 4], dtype=int8)>